name: tnshap
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - h5py>=3.6.0
  - tqdm>=4.62.0
  - jupyter>=1.0.0
  - ipywidgets>=7.6.0
  - pytest>=6.2.0
  - black>=21.0.0
  - flake8>=4.0.0
  - pip:
    - torch>=1.12.0
    - torchvision>=0.13.0
    - torchaudio>=0.12.0
    - shapiq>=0.1.0
    - shap>=0.41.0
    - tensorboard>=2.8.0
    - wandb>=0.12.0